# Generated by Django 5.2.1 on 2025-05-27 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="part",
            field=models.IntegerField(default=10),
        ),
    ]
