# Generated by Django 5.2.1 on 2025-06-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="part",
            field=models.CharField(max_length=100),
        ),
    ]
