# Generated by Django 5.2.1 on 2025-06-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0002_alter_club_part"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="image",
            field=models.ImageField(default="temp_image.jpg", upload_to="club_images/"),
            preserve_default=False,
        ),
    ]
