# Generated by Django 5.2.1 on 2025-06-07 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0003_club_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="club",
            name="image",
        ),
    ]
